
NUM_ACTIONS = 29
GENOME_LENGTH = NUM_ACTIONS
POPULATION_SIZE = 10
OFFSPRING_SIZE = 20
TOURNAMEN_SIZE = 5
MUTATION_PROBABILITY = 0.1
EVALUATION_IT = 10
NUM_GENERATIONS = 200
NUM_ISLANDS = 8
MIGRATION_INTERVAL = 10 
MIGRATION_SIZE = 5
ELITISM_SIZE = 1
EVALUATION_TYPE = "mirror" # mirror or mixed